[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08E44160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/228e1cd74e3de3b8890251e01936614d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08E44490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/228e1cd74e3de3b8890251e01936614d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08E447C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/228e1cd74e3de3b8890251e01936614d