[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08B01590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca2fb945138aec9581f08c08c3b4de2a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08B01810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca2fb945138aec9581f08c08c3b4de2a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AFE060>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ca2fb945138aec9581f08c08c3b4de2a