[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC58C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dec0e8151a32f6bff357a03a05e364e5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC5AE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dec0e8151a32f6bff357a03a05e364e5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC5E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dec0e8151a32f6bff357a03a05e364e5