[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC6F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ac190053bc12a2b3de2818bd06aa4f6b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC7240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ac190053bc12a2b3de2818bd06aa4f6b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C08AC7460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ac190053bc12a2b3de2818bd06aa4f6b